name: Gadabout
title: Gadabout
author: Rex Marzke
#email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  This and that: usually software development related.
show_excerpts: true

#theme: minima
#github_username: rex-tech-home
#linkedin_username: dougbreaux
#rss: rss

# to get latest master
remote_theme: jekyll/minima

minima:
  skin: solarized
  social_links:
    github: dougbreaux
    stackoverflow: "796761"
    linkedin: dougbreaux
  
paginate: 10
#paginate_path: /_posts/page:num/

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false

gems:
#  - jekyll-paginate

# fake Disqus so can do utterances comments without changing base Minima post.html
disqus:
  shortname: fake_disqus_utterances
  
plugins:
 - jekyll-paginate
 - jekyll-feed
 - jekyll-seo-tag
 # for remote themes
 #- jekyll-remote-theme

prose:
  rooturl: '_posts'
  siteurl: 'https://rex-tech-home.github.io/'
  media: 'assets'
